/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day.dao;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        Student st = new Student();
        st.setId(100);
        st.setName("test");

        StudImpl ob;
        ob = new StudImpl();
        ob.update(st);
    }
}
